# Описываем Виртуальные машины
MACHINES = {
  # Указываем имя ВМ
  :"Zadanie_1" => {
              #Какой vm box будем использовать
              :box_name => "mrcitecat/centos-kernel6",
              #Указываем box_version
              :box_version => "1.0",
              #Указываем количество ядер ВМ
              :cpus => 2,
              #Указываем количество ОЗУ в мегабайтах
              :memory => 1024,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Включаем проброс общей папки в ВМ - папка в корне под названием otus_shared
    config.vm.synced_folder ".", "/otus_shared", disabled: false
    # Применяем конфигурацию ВМ
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
    end
  end
end
